### ISSUE TITLE
Slights modifications to compile on Mac OS catalina

### ISSUE THREAD

**Issue by taposk** [cnr-isti-vclab/relight#14]
Hi! This is more a "solve" than an issue! 

I managed to compile on my mac with some slights modifications in src/eigenpca.h, relight-cli/rtibuilder.cpp and rtibuilder.h I had to enter the full path to Eigen (which was installed through homebrew) 
`#include </usr/local/include/eigen3/Eigen/Core or Eigenvalues`

Also I had to add 
```
INCLUDEPATH += /usr/local/Cellar/armadillo/10.2.0/include/ \
    /usr/local/Cellar/jpeg/9d/include/ \
    /usr/local/include \
    /usr/local/Cellar/armadillo/10.2.0/
LIBS += -L/usr/local/Cellar/armadillo/10.2.0/lib/ -larmadillo -ljpeg \
    -L/usr/local/Cellar/jpeg/9d/lib/ -ljpeg 
LIBS += -framework Accelerate
```

to the relight.pro in /relight
If that could help anybody, for once!

Thank you so much for this GUI, it's gonna change my life!

**Comment by ponchio** [comment]
Yes thank you, we are (Alessandro is, actually) working on a decent release for all platform, this will help, thank you.
