### ISSUE TITLE
Validate format of lights.lp

### ISSUE THREAD

**Issue by sepastian** [cnr-isti-vclab/relight#19]
I ran `relight-cli` with an erroneous `lights.lp` file, the number of lights in line 1 was missing.

This is my fault of course, but it would have been helpful if this error had been caught and handled by `relight-cli`. What I got was only a floating point exception:

```
$ relight-cli /in
Floating point exception (core dumped)
```

If `lights.lp` is invalid or missing, `relight-cli` should make this explicit to the user.

**Comment by ponchio** [comment]
I have implemented a more robust .lp file parsing with error reporting. 
Thanks for the feedback.
