### ISSUE TITLE
Usage of libjpeg?

### ISSUE THREAD

**Issue by sepastian** [cnr-isti-vclab/relight#20]
A dependency of relight is `libjpeg`. But looking at the code, there's also `src/jpeg_*coder.*`, which is used by `relight-cli`.

Is libjpeg actually used? If not, should it be used instead of the bundled `src/jpeg_*coder*`?

**Comment by ponchio** [comment]
jpeg_coder is just a wrapper I created for convenience (libjpeg is not really user friendly), and for the possibility to swap to some other image library easily.

I am using libjpeg low level interface mainly for the possibility to read and write jpeg images one line at a time saving a huge amount of RAM, but also for the possibility to change quantization parameters (coefficients are not colors) and disable chroma subsampling.

**Comment by sepastian** [comment]
Right, I should have been reading more carefully, thanks for the clarification!
