### ISSUE TITLE
Relight-cli: error when using the reconstruction error options (-e and -E)

### ISSUE THREAD

**Issue by irinaciortan** [cnr-isti-vclab/relight#25]
Hi,

I used relight-cli in default mode for a dataset and it worked fine. However, when activating the reconstruction error option (-e), I got the following error: 
![image](https://user-images.githubusercontent.com/44868479/118872653-14282c80-b8e9-11eb-826c-899c983ee52b.png)

Similarly, when I tried the leave-one-out option -E, I got this. It seems that the name of the image to be excluded is not deleted from the modified .lp file, while the total number of images is updated?
![image](https://user-images.githubusercontent.com/44868479/118872868-581b3180-b8e9-11eb-9c2e-183c89dc73d5.png)

Thank you for the nice work!

**Comment by ponchio** [comment]
I didn't test those options in a long time... anyway they should be fixed now.
Thanks for the feedback.
