### ISSUE TITLE
Question: normals extraction with relight-cli, colors seem off?

### ISSUE THREAD

**Issue by irinaciortan** [cnr-isti-vclab/relight#26]
Hi,

I have extracted normal maps for my data  (using -n option) and  the exported RGB normal maps  don't look correct. They are mostly pink. When visualizing the same data with relight, the normal layer visualization makes more sense. So I'm wondering if this is a problem of the data (input colorspace?) and/or is there something going wrong in relight-cli normal image writing?

Thanks!

**Comment by ponchio** [comment]
It was a problem with the output colorspace (trying to conform to a different standard). In the meanwhile I improved the normals quality too.

**Comment by irinaciortan** [comment]
Yes, looks better. Even though to me it still looks as if the green channel were reversed with the red one.

**Comment by ponchio** [comment]
Red channel is on the X axis and Green channel is on the Y axis, RGB -> XYZ

I'm not really sure this is the correct standard...
