### ISSUE TITLE
Use of -D in relight-cli

### ISSUE THREAD

**Issue by irinaciortan** [cnr-isti-vclab/relight#28]
I've been using the -D option, but I think I'm not calling it correctly since I either get no images in the directory, or only blank images or the same image repeated. Would it be possible to have an example with it?

Thanks!

**Comment by ponchio** [comment]
The code was using the lights stored in the info.json, but form PTM and HSH the lights are not stored hence the problem.

The code should be called as such:

relight-cli <input dir> <output dir> -b ptm -p 18 -D tmp

The RTI is first computed then all the images reconstructed.
