### ISSUE TITLE
Multiple relight-viewer.js on single page

### ISSUE THREAD

**Issue by sepastian** [cnr-isti-vclab/relight#5]
Hello, I'm trying to add multiple relight-viewer.js instances to a single page, into separate divs. The divs are created and sized correctly, but only one RTI is displayed. It appears as if the second RTI gets placed on top of the first one, this can be seen briefly when loading the page. Sometimes the first RTI will be displayed, sometimes the second one.

I am executing this code for each RTI to display.

```
# relight_id is the unique ID of the div to fill
new RelightViewer(relight_id,{                        
                layers: [                                         
                    {                                             
                        position: [0,0],                          
                        rotation: 0,                              
                        url: data.rti_path,                       
                        layout: 'image'                           
                    }                                             
                ],                                                
                fit: true                                         
            })                                                    
            return false;   
```

What am I doing wrong? Is relight-viewer.js capable of displaying multiple instances on a single page?

**Comment by ponchio** [comment]
Sorry, didn't see the issue.

There was some problem with the nameing of the divs and the event dispatching. It should be fixed now (bar some testing...)
