### ISSUE TITLE
Icons barely visible

### ISSUE THREAD

**Issue by EloiGattet** [cnr-isti-vclab/relight#55]
![Capture d’écran, le 2023-03-28 à 11 56 50](https://user-images.githubusercontent.com/91476356/228200400-e3448c4d-b3d7-462c-9103-e0bc31ba4df6.png)
The icons for editing and deleting a sphere are barely visible, could a higher contrast one be used?
They do appear clearly in dark mode : 
![Capture d’écran, le 2023-03-28 à 11 57 50](https://user-images.githubusercontent.com/91476356/228200653-a0cf566d-9a01-4a77-8830-b6b688ad3f6c.png)

Thanks!!

**Comment by ponchio** [comment]
Fixed (hopefully).
