### ISSUE TITLE
Merge data is twice the size of regular RTI

### ISSUE THREAD

**Issue by EloiGattet** [cnr-isti-vclab/relight#59]
The result of the "merge" tool gives a folder more than twice the size the previous operation. Maybe it's a jpeg compression problem?

<img width="825" alt="Capture d’écran, le 2023-06-14 à 08 33 10" src="https://github.com/cnr-isti-vclab/relight/assets/91476356/b64f5772-6e9b-458e-8876-ff0b91a8f9fd">

**Comment by ponchio** [comment]
Now merge tools keeps the same quality of the original RTIs or you can specify a final quality using -q option.
