### ISSUE TITLE
Relight crashes when trying to build RTI result on Windows 10

### ISSUE THREAD

**Issue by andreas1974** [cnr-isti-vclab/relight#61]
Relight crashes after a few seconds when I click the build button. I have added 9 pictures, located the sphere, and the highlight was detected.
I get to chose a file name and then some progressbars show up (no progress) and the program crashes.

I have installed vc_redist.x64.exe and restarted the computer.

I have installed Python 3.11 and run the pip commands.
However, while doing that I got an error trying to follow the installation instructions. I had to change 

`pip install opencv-python sklearn pyvips`
into this:
`pip install opencv-python scikit-learn pyvips`

Could this be a problem, that Relight still expects **sklearn**, and that it is no longer supported by pip?

I have added the path to Python.exe in the Relight preferences.
(There is also a setting for "scripts folder" in the preferences. I have no idea what to put there.)

I have added the 32 bit version of "libvips" to a folder and added the path to its bin folder to system environment PATH. (There is really no good information on how to install libvips on Windows, but adding its path to the PATH variable ought to be enough, right?).

Anyway, no change. Relight still crashes. What could be the problem?

**Comment by andreas1974** [comment]
Now I finally found out what caused the error.
My path to the images, and to the output subfolder, contained the Swedish letter "å".

**Comment by andreas1974** [comment]
This was closed without a comment... Please make a comment or refer to the fix, if there was one.
Have you fixed the issue so that image paths will work even when they contain Swedish letters "å, ä, ö"?

**Comment by ponchio** [comment]
Sorry forgot the comment, 
           I fixed the bug some times ago. Now RelightLab should work with any Utf8 characters.
although I could not test on any platform.

https://github.com/cnr-isti-vclab/relight/commit/d490ebfb5e3e0b6122e0357a666236ea2a63676f
