### ISSUE TITLE
What is relight-merge for?

### ISSUE THREAD

**Issue by BeebBenjamin** [cnr-isti-vclab/relight#65]
Hey I am teaching myself how to use Relight in place of RTIBuilder and RTIViewer, I was wondering what is the use case for the application called `relight-merge`.

**Comment by ponchio** [comment]
Ciao,
        relight-merge has been created to make rti panoramas. It brings 2
or more RTI (in the same base: ptm or hsh) in the same quantization space,
so that the coefficient planes can be combined. I am working on the new
interface for relightlab and will integrate rti panorama functionality in
it.

If you need any advice, have some feature request, want to test the new
interface, contact me at ***@***.*** and we can have a chat about it.

**Comment by BeebBenjamin** [comment]
Thanks for the clarification. I have been merging RTIs using Metashape, so if I am able to do this using Relight, it will be much better. I cannot see your email, GitHub has censored it.  So I will find it online for the VCL at Pisa.

**Comment by BeebBenjamin** [comment]
I cannot get relight-merge to work.

What does `Rti basis for /home/richard/tool-216/photos1/chunk_2/rti/info.json is different.` mean?

**Comment by BeebBenjamin** [comment]
OK, I realise relight-merge only works for ptm and hsh, and not rbf.

I am getting another error now: `Could not create remapped RTI directory: info.json`

How do  you specify an output folder?

**Comment by ponchio** [comment]
The last argument of the command line is the output folder:

relight-merge <first_ptm/info.json> <second_ptm/info.json> <output_folder>

**Comment by BeebBenjamin** [comment]
I still get the same error `Could not create remapped RTI directory`

**Comment by ponchio** [comment]
Please write the command line here... (and then I will clarify error reporting something more informative).

**Comment by BeebBenjamin** [comment]
```bash
./relight-merge /home/richard/tool-216/photos1/chunk_1/rti/info.json /home/richard/tool-216/photos1/chunk_2/rti/info.json /home/richard/tool-216/photos1/chunk_3/rti/info.json /home/richard/tool-216/photos1/chunk_4/rti/info.json /home/richard/tool-216/photos1/chunk_5/rti/info.json /home/richard/tool-216/photos1/chunk_6/rti/info.json /home/richa
rd/tool-216/photos1/chunk_7/rti/info.json /home/richard/tool-216/photos1/chunk_8/rti/info.json /home/richard/tool-216/photos1/chunk_9/rti/info.json /home/richard/tool-216/photos1/chunk_10/rti/info.json /home/richard/Documents/
```

**Comment by ponchio** [comment]
Ok, here is the issue: the folder /home/richard/Documents exits, you have to provide the path to a folder that does not (yep, sorry!) for example: /home/richard/Documents/tool-216

**Comment by BeebBenjamin** [comment]
OK, I am getting Segmentation fault (core dumped) now and then a directory called `info.json`

**Comment by ponchio** [comment]
If you can send me the samples I will ingestigate the problem and fix the code. Sorry for the mess, it was just a tool for myself, but thanks for alfa-testing it :)

**Comment by BeebBenjamin** [comment]
OK, what files do you need?  Just the rti files, or do you need the jpgs too?

**Comment by ponchio** [comment]
Just the rti files, I will fake the jpegs, it could well be a windows related problem, but let's start with replicating functionality in my machine.

**Comment by BeebBenjamin** [comment]
OK, I have sent you a link to dropbox to your gmail.  Thanks for you help!

**Comment by BeebBenjamin** [comment]
I generated these files using relight-cli command line:

```bash
./relight-cli /home/richard/tool-216/photos1/chunk_1/jpg /home/richard/tool-216/photos1/chunk_1/rti -n -m -b ptm -p 3
```
One thing I did notice is relight-cli doesn't make any files with the extension `.ptm`.

**Comment by ponchio** [comment]
relight-cli can generate files both in the 'legacy" formats (.ptm and .rti) if instead of a folder name as an argument you specify a .ptm filename, like this:

./relight-cli /home/richard/tool-216/photos1/chunk_1/jpg /home/richard/tool-216/photos1/chunk_1/rti.ptm -n -m -b ptm -p 3

in general, if you run a command line tool without arguments:

./relight-cli

you get a brief help.

**Comment by BeebBenjamin** [comment]
OK, I have compiled the new version and relight-merge works.  I also needed to change the name of the folders to things like rti1, rti2, rti3.
