### ISSUE TITLE
Latest relight-cli experiences core dumps on Ubuntu 22.04

### ISSUE THREAD

**Issue by BeebBenjamin** [cnr-isti-vclab/relight#66]
When compiling relight-cli from the latest commit on Ubuntu 22.04 64bit, it will dump cores and abort.

```bash
./relight-cli /home/richard/tool-216/photos1/chunk_1/jpg /home/richard/tool-216/photos1/chunk_1/rti -n -m -b hsh -q 100
Skipping cropped lines... %100
Sampling images: %100relight-cli: /home/richard/gitkraken/relight/relight-cli/rtibuilder.cpp:445: MaterialBuilder RtiBuilder::pickBaseHSH(std::vector<Vector3<float> >&, Rti::Type): Assertion `nplanes == 27 || nplanes == 12' failed.
Aborted (core dumped)
```
The work around is to use the last release.

**Comment by ponchio** [comment]
You need to add -p 27 (or -p 12 if you an hsh with only 4 images).

I have converted the assert into an error report and clean exit.

**Comment by BeebBenjamin** [comment]
OK understood.  So the number of planes is involved in the model, you use 27 if you have more than 4 images, and 12 if you only have 4.  I think being explicit with the user that this flag is not optional for this fitter was the best outcome, thanks for making the change.
