### ISSUE TITLE
Batch  processing hundrets of stacks

### ISSUE THREAD

**Issue by MiB76** [cnr-isti-vclab/relight#68]
Hello, is there a way of batch processing hundreds of stacks with the same calibration file (lp file) via command line or any kind of scripting?
Best, Michael

**Comment by EloiGattet** [comment]
Hello,
Yes, you can use the relight-cli, which is a command line interface for Relight. Just place the lp file in the same folder as the pictures and call the command line tool. 
I use it regularly with python scripts and/or bash scripts. 
As I saw in another post you're using only 8 lights (state of the art says 24 is a minimum for a good result), I recommand that you use "PTM" algorithm which is the simplest :
`relight-cli /rti-data /output/ -b ptm -p 18`


Here is an example of a python and a bash script:
Python Script:

```python
import os
import subprocess

input_dir = '/path/to/input'
output_dir = '/path/to/output'
relight_cli_path = '/path/to/relight-cli'

# Process each folder in the input directory
for folder_name in os.listdir(input_dir):
    input_folder = os.path.join(input_dir, folder_name)
    output_folder = os.path.join(output_dir, folder_name)
    # Ensure it's a directory
    if os.path.isdir(input_folder):
        # Run the command
        subprocess.run([relight_cli_path, input_folder, output_folder, '-b', 'ptm', '-p', '18'])
```

Bash Script:

```bash
#!/bin/bash

INPUT_DIR="/path/to/input"
OUTPUT_DIR="/path/to/output"
RELIGHT_CLI="/path/to/relight-cli"

# Process each folder in the input directory
for folder in "$INPUT_DIR"/*; do
  if [ -d "$folder" ]; then
    FOLDER_NAME=$(basename "$folder")
    "$RELIGHT_CLI" "$folder" "$OUTPUT_DIR/$FOLDER_NAME" -b ptm -p 18
  fi
done
```

Make sure to give execution permissions to the bash script using `chmod +x scriptname.sh` before running it.

**Comment by MiB76** [comment]
Thank you very much for this very detailed answer that helps a lot, EloiGattet!
I will try your scripts soon.
