### ISSUE TITLE
onload example

### ISSUE THREAD

**Issue by lmaylein** [cnr-isti-vclab/relight#69]
Hi,

I am currently trying to find out how I can use the documented onload (is it realy "onload" or should it be "onLoad"?) function.

```
      rti = new RelightViewer(el,
        {
          layers: [
                {
                        position: [0, 0],
                        rotation: 0,
                        url: $(el).attr('data-uri'),
                        layout: 'image',
                        visible: true,
                }
          ],
          fit: true,
          pos: { x:0, y:0, z:0, a:0 },
          rotation: 0,
          scale: 1.0,
          background: [0.7, 0.7, 0.7, 1],
        })
      rti.onload = function(t) {console.log('test')}
```
doesn't work for me. The function is never triggered.
Since the model to be displayed is quite large, I would like to display a spinner during the loading process.

Leonhard Maylein

**Comment by ponchio** [comment]
Hi, 
           I should definitely update the documentation, expecially since the web viewer is basically discontinued and replaced with [OpenLIME](https://github.com/cnr-isti-vclab/openlime) viewer, again needing better documentation, but feel free to ask.
           
In any case: onLoad is a function that adds a callback:

rti.onLoad( (t) => { console.log('test'); } );

If the project is big you should really use deepzoom (or tarzoom which is basically the same thing but using 2 files instead of a gazillion), that would remove the need for a spinner.

Federico

**Comment by lmaylein** [comment]
`rti.onLoad( (t) => { console.log('test'); } );`

results in

"rti.onLoad  is not a function"

Good to know that this viewer is no longer being developed. I will have a look at OpenLIME. I was just surprised that there is a relatively new release here, but the one of OpenLIME is a bit older.
Many thanks for the great work.

**Comment by ponchio** [comment]
Sorry for not testing the line of code (I was in a hurry), the callback is
per layer, not on the viewer, the actual line should have been:

rti.layers[0].onLoad(() => console.log('loaded'));

Only the viewer is not supported anymore (nothing wrong in using it, by the
way), the applications to create the rtis (relight-cli, relightlab) are
actively developed.

Federico

**Comment by lmaylein** [comment]
Okay. Thanks for the clarification.
