### ISSUE TITLE
Normal Map Export artifacts

### ISSUE THREAD

**Issue by thomasgraichen** [cnr-isti-vclab/relight#78]
The normal map export produces (compression?) artifacts in the image.
Here e.g. using the fish fossil example dataset from [chi.org](https://culturalheritageimaging.org/What_We_Offer/Downloads/Process/index.html). 

Artifacts all over on the normal map generated with relight, most prominent in the two large horizontal creases on the upper third of the fossil:
![relightNormals](https://github.com/user-attachments/assets/5d1d7680-7b6e-4220-936e-9b37d46157e9)

Here the normal map from the rtiviewer for comparrison:
![rtiviewerNormals](https://github.com/user-attachments/assets/85ebef86-f4e4-4c87-80d9-289b82e7c530)

Here as a gif for better visualization:
![normals_relightVSrtiviewer](https://github.com/user-attachments/assets/cf173dc2-33ac-4a10-9e8e-ca56c4daed6b)

**Comment by ponchio** [comment]
Hi, I am not sure how you created that normal map in relightlab.

I downloaded the fish sample, built the normal map using Export -> Export normals menu, and created a png image which is basically the rtiviewer image you sent.

Could you detail theprocess?

**Comment by thomasgraichen** [comment]
Hi, thanks for the quick response!
Same process here. I have tried it again, the errors are always there, but not always in the same place. I think they might be a result of how the normal map is calculated.
Here are some tests, all from relight, all generated a few seconds apart:

![normals_test_01](https://github.com/user-attachments/assets/0d97ca51-6124-4f99-b6f3-88d4a39d6dd1)
![normals_test_02](https://github.com/user-attachments/assets/57380a9d-922d-4614-b1b9-531fdae1cd6b)
![normals_test_03](https://github.com/user-attachments/assets/023a927a-0e9d-408d-94fa-575da3d959ed)
As you can see, I always get artifacts, sometimes less, always in different places.

**Comment by ponchio** [comment]
I suspect that there might be a problem with the parallelization of the algorithm (I fixed a race condition on July 30), this is very OS/CPU dependent.

Which version are you using? Could you try the latest commit, the executable can be found here: https://github.com/cnr-isti-vclab/relight/actions/runs/10165375626

Thanks.

**Comment by thomasgraichen** [comment]
Perfect, your latest commit fixed it! 👍 
![normals_test_10](https://github.com/user-attachments/assets/0ed85120-f1d7-4301-a2fe-64fda78b0158)

I noticed you also added a ply export option, that is awesome!
Thank you very much for your work :)
